### ISSUE TITLE
Add ability to disable KSM and Controlplane scraping

### ISSUE THREAD

**Issue by invidian** [newrelic/newrelic-infra-operator#104]
To support https://github.com/newrelic/nri-kubernetes/issues/201, once we split nri-kubernetes into two pieces, we will have to make infra-operator to not scrape KSM or Controlplane, as it will be done by a dedicated daemon.

**Comment by paologallinaharbur** [comment]
Context: currently every agent not running together with KSM has the option `DISABLE_KUBE_STATE_METRICS` enabled
