### ISSUE TITLE
Make solution compatible with new k8s arch

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/newrelic-infra-operator#113]
Theoretically we should be able to solve the issue by injecting containers in a different way.
 - Inject agent and “kubelet” component on all pods
 - No reason to inject KSM as well since it should scrape KSM only once and it is a deploy as everything else
 - Verify how a migration would work and document it in the Fargate docs
 - Monitor control plane is not that important since it is managed, but we can for sure do something for the apiServer(currently not supported)

**Comment by davidgit** [comment]
Closing it because of https://github.com/newrelic/newrelic-infra-operator/issues/135
