### ISSUE TITLE
newrelic-infra-operator not deploying nri-kube-events integration on Fargate

### ISSUE THREAD

**Issue by nedl86** [newrelic/newrelic-infra-operator#120]
## Description

There seems to be a bug in the operator where we are accidentally using the same name for the volumes of what we inject and nri-kube-events.

## Steps to Reproduce

Deploy latest version of newrelic-infra-operator on Fargate cluster. Events integration does not deploy successfully.

## Expected Behavior

Events integration deploys successfully.

**Comment by paologallinaharbur** [comment]
Hello!
Can you share the yaml of the nri-kube-events with the injected sidecar? with version of the `newrelic-infra-operator` are you running?

The release v0.4.0 was fixing that issue https://github.com/newrelic/newrelic-infra-operator/releases/tag/v0.4.0 are you running an updated version of the operator? If so can you share the yaml of the operator and the content of the config map mounted?

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
