### ISSUE TITLE
Make solution 100% compatible with nri-kubernetes v3

### ISSUE THREAD

**Issue by davidgit** [newrelic/newrelic-infra-operator#135]
Theoretically we should be able to solve the issue by injecting containers in a different way.

- Inject agent and “kubelet” component on all pods
- No reason to inject KSM as well since it should scrape KSM only once and it is a deploy as everything else
- Verify how a migration would work and document it in the Fargate docs
- Monitor control plane is not that important since it is managed, but we c an for sure do something for the apiServer(currently not supported)

**Comment by paologallinaharbur** [comment]
Currently the Fargate solution is still injecting v2 version. In an hybrid scenario the user could monitor fargate with v2 and not-fargate nodes with v3 without issue. The APIServer component is still not scraped since CP monitoring is disabled if fargate=true

**Comment by paologallinaharbur** [comment]
Internal discussion https://newrelic.slack.com/archives/C8A4BCGSF/p1646098342013819
