### ISSUE TITLE
Garbage collect unused ClusterRoleBinding subjects and Secrets

### ISSUE THREAD

**Issue by invidian** [newrelic/newrelic-infra-operator#3]
Webhook creates side effects, so we should figure out the way to periodically clean up those objects when they are no longer needed. For secrets, perhaps we could use `metadata.ownerReferences` to automatically clean up secrets when all owner objects (Pods) are removed?

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
