### ISSUE TITLE
Consider adding controller for ClusterRoleBinding

### ISSUE THREAD

**Issue by invidian** [newrelic/newrelic-infra-operator#6]
If one removes all subjects from our `ClusterRoleBinding`, monitoring will break until pods are recreated.

[K8s docs](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#side-effects) says mutating webhook must have controller to periodically re-evaluate side-effects.

I think Secrets don't need a controller, as we will ensure secret exists on every pod creation anyway.

We could check what happens to secret inside pod when you delete the secret while pod is running.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
